apiVersion: backstage.io/v1alpha1
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Warehouse search API
  description: define dependency providers and consumers
spec:
  type: service
  lifecycle: QAT
  owner: group:Enterprise Services Development
  system: QA region
  dependsOn:
    - resource:default/resource-name
  providesApis:
    - Warehouse search API
  consumesApis:
    - petstore
