---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: WarehousesearchAPI
  description: define dependency providers and consumers
  annotations: 
    jenkins.io/job-full-name: ECOM_WCS_REACT/WCS_MSC_poc
spec:
  type: service
  lifecycle: QAT
  owner: group:Enterprise Services Development
  system: QA region
  providesApis:
    - Warehouse search API
  consumesApis:
    - petstore
