apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: WarehousesearchAPI
  description: define dependency providers and consumers
  providesApi: WarehouseLocatorAPI
  annotations: 
    github.com/project-slug: handysnacks/logistics
    backstage.io/techdocs-ref: dir:.
    jenkins.io/job-full-name: ECOM_WCS_REACT/WCS_MSC_poc
spec:
  type: service
  lifecycle: QAT
  owner: group:Enterprise Services Development
  system: QA region
  providesApis:
    - 
  consumesApis:
    - Wayback archive API
  providesApis:
    - Warehouse search API
    - hello-world 
  consumesApis: petstore
  dependsOn:
    - component:default/www-artist
