apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Enterprise Services Development
  description: handysnacks ecommsite
  providesApi: Warehouse search API    
  annotations:
    github.com/project-slug: handysnacks/logistics
    backstage.io/techdocs-ref: dir:.
    jenkins.io/job-full-name: ECOM_WCS_REACT/WCS_MSC_poc
spec:
  type: Enterprise Services Development
  lifecycle: ADT
  owner: eComm
  version: "1.0"
  system: testing
  providesApis: 
    - petstore
  consumesApis:
    - {Mobile,EComm}
