apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: SAMPLE-archive
  title: SAMPLE archive API
  description: Archive API for the wayback machine
spec:
  type: openapi
  lifecycle: production
  owner: team-alpha
  definition:
    $text: https://github.com/APIs-guru/openapi-directory/blob/main/APIs/archive.org/wayback/1.0.0/openapi.yaml
