apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: SAMPLE-archive
  title: SAMPLE archive API
  description: Archive API for the wayback machine
spec:
  type: openapi
  lifecycle: production
  owner: team-alpha
  definition:
    $text: https://github.com/handysnacks/logistics/blob/main/openapi.yaml
